dbt_project_tcp:
  outputs:
    dev:
      account: ''
      database: OPENFLOW_SLACK
      role: ACCOUNTADMIN
      schema: SLACK
      threads: 1
      type: snowflake
      user: ''
      warehouse: compute_wh
  target: dev